verify tags selected exists

diff --git a/.github/workflows/tag-test.yaml b/.github/workflows/tag-test.yaml
--- a/.github/workflows/tag-test.yaml
+++ b/.github/workflows/tag-test.yaml
@@ -1,23 +1,30 @@
 name: Performance Test against Tags
 on:
-    workflow_dispatch:
-        inputs:
-            startTag:
-                description: 'Tag to begin with'
-                required: true
-                default: '5.9.2'
-                type: string
-            endTag:
-                description: 'Tag to end with'
-                required: false
-                type: string
-                default: '5.8.1'
+  workflow_dispatch:
+    inputs:
+      startTag:
+        description: 'Tag to begin with'
+        required: true
+        default: '5.9.2'
+        type: string
+      endTag:
+        description: 'Tag to end with'
+        required: false
+        type: string
+        default: '5.8.1'
 
 jobs:
-    determine-tag-range:
-        runs-on: ubuntu-latest
-        steps:
-            - run: |
-                  echo "Start tag selected: ${{ github.event.inputs.startTag }}"
-                  echo "End Tag selected: ${{ github.event.inputs.endTag }}"
-                  echo "Environment: $ENVIRONMENT"
+  determine-tag-range:
+    runs-on: ubuntu-latest
+    steps:
+      - run: |
+      if [ ! $(git tag -1 "${{ github.event.inputs.startTag }}" ]; then
+        echo "::error::The start tag you've requested does not exist. Verify the tag you've requested (${{ github.event.inputs.startTag }}) exists."
+        exit 1
+      fi
+
+      if [ ! $(git tag -1 "${{ github.event.inputs.endTag }}" ]; then
+        echo "::error::The end tag you've requested does not exist. Verify the tag you've requested (${{ github.event.inputs.startTag }}) exists."
+        exit 1
+      fi
+
